### ISSUE TITLE
我下载项目以后有这个错误

### ISSUE THREAD

**Issue by Yearnday** [Atreus1125/ShoppingSystem#1]
异常报告

消息 在 [123] 行处理 [/index.jsp] 时发生异常

描述 服务器遇到一个意外的情况，阻止它完成请求
大佬能解答嘛

**Comment by Atreus1125** [comment]
你可以看看Java控制台上的具体错误，我猜测可能是数据库连接的问题，再或者可能是Tomcat配置问题

**Comment by Yearnday** [comment]
> 你可以看看Java控制台上的具体错误，我猜测可能是数据库连接的问题，再或者可能是Tomcat配置问题

解决了，是我的tomcat的问题，谢谢大佬
