### ISSUE TITLE
CustomUtil这个工具类的作用是啥

### ISSUE THREAD

**Issue by Yearnday** [Atreus1125/ShoppingSystem#2]
大佬，CustomUtil这个工具类的作用是啥

**Comment by Atreus1125** [comment]
自定义工具类，主要是为了在控制台输出不同于常规消息的调试信息（两个函数分别用于输出调试信息所在文件位置和想查看的参数值），可以指定输出颜色

**Comment by Yearnday** [comment]
感谢大佬的解答
